### ISSUE TITLE
Remontée métier: taguer proprement le médecin traitant

### ISSUE THREAD

**Issue by flachalESEA** [ansforge/IG-fhir-cercle-de-soins#17]
## Description du problème
L'idée est de bien identifier le médecin traitant comme membre du cercle de soins.

## Fichier•s concerné•s
Profil CDS_IHECareTeam

## Solution proposée

AMHA ça vaudrait le coup de binder quelque chose dans participant.role ?

**Comment by flachalESEA** [comment]
Bon à priori c'est bon dans le ci-build car bindé à http://hl7.org/fhir/R4/valueset-participant-role.html

Edit: en fait j'avais du lire trop vite, c'est un binding en example. Ça vaudrait le coup d'avoir un JDV avec "Médecin Traitant", "Intervenant social" ce genre de choses, en binding extensible histoire d'être un peu ouvert. J'ai rien trouvé dans le NOS qui me va bien.

**Comment by nriss** [comment]
Cf https://github.com/ansforge/IG-fhir-cercle-de-soins/blob/9d22a8ff91a21e9136d08402071d3ebda19d22c2/input/fsh/profiles/CDS_IHECareTeam.fsh#L28C1-L28C1

**Comment by nriss** [comment]
Hello @flachalESEA, pourrais-tu me fournir la liste des concepts qui seraient intéressants ?
Je pense rajouter un VS et un CS ici et le supprimer à terme quand ça sera uniformisé

**Comment by flachalESEA** [comment]
Je vais aller faire un tour du côté de ma direction Projet Parcours et je reviens vers toi. Je pense que les référents/gestionnaires de parcours pourraient être intéressants par exemple, médecin traitant c'est une certitude.
