### ISSUE TITLE
Faut il autoriser le Practitioner dans participant.member?

### ISSUE THREAD

**Issue by nriss** [ansforge/IG-fhir-cercle-de-soins#18]
https://github.com/ansforge/IG-fhir-cercle-de-soins/blob/9d22a8ff91a21e9136d08402071d3ebda19d22c2/input/fsh/profiles/CDS_IHECareTeam.fsh#L28C1-L28C1

Proposition Florent Lachal : binder participant.role (dans CareTeam) à http://hl7.org/fhir/R4/valueset-participant-role.html serait suffisant

**Comment by flachalESEA** [comment]
Oui.

**Comment by nriss** [comment]
Je clos car doublon avec https://github.com/ansforge/IG-fhir-cercle-de-soins/issues/17
