### ISSUE TITLE
Faut-il spécifier une organisation interne dans le cadre du CDS ?

### ISSUE THREAD

**Issue by nriss** [ansforge/IG-fhir-cercle-de-soins#30]
## Description du problème
Cf https://github.com/ansforge/IG-fhir-cercle-de-soins/pull/27#discussion_r1524628300

**Comment by flachalESEA** [comment]
Pour l'enlever. Pas besoin d'un profil spécifique pour décrire une OI, à l'instar de ce qui a été fait sur la modélisation ROR. 

Il ne faut pas supprimer la notion fonctionnelle d'OI pour autant de ce CI-SIS, nous avons en région des cercles de soins associés spécifiquement à des services hospitaliers. 

Du coup, pour l'enlever et exprimer les trois notions (OI, EG et EJ) au travers d'un même profil, et le profil AS_Organization est  moins bien fichu que celui du ROR sur ce point (exemples: le narratif de l'attribut name ou encore le fait qu'il n'y ait pas de slices pour un identifier d'OI en revanche sur le type le jeu de valeur est utilisable).
