### ISSUE TITLE
Faut-il créer un profil Patient pour le Cercle de Soins ?

### ISSUE THREAD

**Issue by cdelanchy** [ansforge/IG-fhir-cercle-de-soins#9]
## Description du problème

Le profil utilisé dans le Cercle de Soins est le profil FrPatient. Pour avoir un Cercle de Soins complet, nous souhaitons avoir des ressources patients bien complétées, notamment sur les éléments suivants : 
* meta
* identifier
* telecom
* address

Le narratif du volet (pdf) contient le texte suivant : 

> La ressource Patient est identifiée pour véhiculer les informations, notamment d’identité, du sujet du
cercle de soins.
> Le concept métier « PersonnePriseCharge » correspond au profil français « FrPatient » du package
hl7.fhir.fr.core 1.1.0.
> Le profil FrPatient n’est pas contraint dans le présent volet mais en termes organisationnels, il est
demandé de faire le maximum pour obtenir les informations spécifiées dans les SFE :
>* élément « meta » obligatoire
« meta » : informations relatives à la gestion des classes et des données,
>* élément « identifier » obligatoire
« identifier » : identifiant(s) de la personne prise en charge (identifiants de santé, identifiants
locaux, …,
>* élément « telecom » obligatoire
« telecom » : adresse(s) de télécommunication de la personne prise en charge (numéro de
téléphone, adresse e-mail URL, etc.),
>* cardinalité de l’élément « address » contrainte à [1..1]
« address » : adresse(s) de correspondance de la personne prise en charge.

Ces contraintes nécessitent-elles de créer un profil Patient pour le CdS ?
Ou bien suffit-il d'indiquer que l'on souhaite que ces éléments soient complets dans l'utilisation du CdS ? Le cas échéant, le mot "obligatoire" semble trop fort dans le narratif que l'on pourrait laisser en recommandation dans l'IG.

Qu'en pensez-vous ?

**Comment by nriss** [comment]
Je propose que l'on ne reprofile pas et que l'on nuance les propos, précisant que ces éléments devraient être remplis, et qu'une étude approfondie avec un nouveau profiling de la ressource patient pourra avoir lieu dans une prochaine release

**Comment by nriss** [comment]
Profil patient créé https://ansforge.github.io/IG-fhir-cercle-de-soins/main/ig/StructureDefinition-cds-fr-patient.html

**Comment by cdelanchy** [comment]
Du coup, @nriss, je ne comprends pas la création du profil si l'idée était justement de ne pas le faire en nuançant plutôt les propos dans l'IG ?

> Je propose que l'on ne reprofile pas et que l'on nuance les propos, précisant que ces éléments devraient être remplis, et qu'une étude approfondie avec un nouveau profiling de la ressource patient pourra avoir lieu dans une prochaine release

**Comment by nriss** [comment]
En reprenant les tableaux de description des profils dans les pdf, je suis retombé sur ça :
![image](https://github.com/ansforge/IG-fhir-cercle-de-soins/assets/48218773/a8ca4fb1-8df7-4575-9836-fb065e0ed6ba)
https://esante.gouv.fr/sites/default/files/media_entity/documents/cisis-tec_specifications_techniques_gestion_cercle_soins_v1.2.pdf (page 20)

Je trouve ça assez bizarre de mettre ces contraintes en narratif et préfère les mettre en technique via un profil pour pouvoir tester le respect de ces contraintes.
Qu'en penses-tu ? Est-ce nécessaire de mettre ces contraintes ? Est-ce que tu les utilises ?
Totalement ouvert aux changements si nécessaire :)

A noter également que la création d'un profil amène l'utilisation d'une autre URL canonique

**Comment by nriss** [comment]
J'ai fait le test ici : https://github.com/ansforge/IG-fhir-cercle-de-soins/pull/34

**Comment by cdelanchy** [comment]
Je n'ai pas encore de retours terrains sur l'utilité du truc. Donc pour l'instant, je ne les utilise pas.

Et plus j'y repense, plus je crois qu'il ne faut pas profiler et garder le FrPatient. Les contraintes évoquées sont principalement l'identifiant (qui me semble la plus importante) et qui est obligatoire réglementairement avec l'INS (si c'est possible).
Les parties telecom et address sont intéressantes si renseignées, mais en fait, l'important dans le Cercle de Soins n'est pas tellement la complétude des informations patients, mais celles des professionnels (on cherche à contacter les membres du CdS, pas le patient), àmha.

Je verrai bien l'utilisation du FrPatient dans ces spécifications nationales (dans le CI-SIS), et justement permettre à chacun de faire un IG local basé dessus pour son implémentation avec d'autres contraintes plus spécifiques si besoin (en région par exemple, même si je ne pense pas que nous le ferons).

Vous en pensez quoi ? (et je tag @flachalESEA pour son éclairage, car je crois qu'il va commencer à jouer avec ce truc aussi :D)

**Comment by nriss** [comment]
Totalement aligné!

Je vais continuer sur cette PR : https://github.com/ansforge/IG-fhir-cercle-de-soins/issues/9#issuecomment-2140254032

**Comment by flachalESEA** [comment]
Salut Clotaire, 

Effectivement je suis vos travaux sur CDS :) . Pour le sujet de l'issue, je suis aligné avec toi: on garde FrPatient, on peut toujours ensuite en région surspécifier si besoin et préciser un petit qq chose dans le narratif. 

Ok avec le fait aussi que la plusvalue de CDS c'est le ... CDS.  Le patient est la pour le rapprochement pas vraiment pour les infos liées.
